#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=MMC-over-GPIO configuration module
LUCI_DEPENDS:=+kmod-mmc-over-gpio
SECTION:=xNN's Feed
CATEGORY:=xNN's Feed
SUBMENU:=DLINK
include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
